# Generated by Django 6.0.1 on 2026-01-20 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_email', models.EmailField(db_column='User_Email', max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=255, null=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
                ('account_created', models.DateTimeField(auto_now_add=True, db_column='Account_Created', null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.CharField(db_column='Alert_ID', max_length=10, primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, db_column='Message', max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='Created_at', null=True)),
            ],
            options={
                'db_table': 'alert',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('asset_id', models.CharField(db_column='Asset_ID', max_length=10, primary_key=True, serialize=False)),
                ('asset_name', models.CharField(blank=True, db_column='Asset_Name', max_length=50, null=True)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=50, null=True)),
            ],
            options={
                'db_table': 'assets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('club_id', models.CharField(db_column='Club_ID', max_length=10, primary_key=True, serialize=False)),
                ('club_name', models.CharField(blank=True, db_column='Club_Name', max_length=50, null=True)),
                ('club_funds', models.IntegerField(blank=True, db_column='Club_Funds', null=True)),
                ('reg_fee', models.IntegerField(blank=True, db_column='Reg_fee', null=True)),
                ('advisor_name', models.CharField(blank=True, db_column='Advisor_Name', max_length=50, null=True)),
                ('advisor_email', models.CharField(blank=True, db_column='Advisor_Email', max_length=50, null=True)),
                ('advisor_initial', models.CharField(blank=True, db_column='Advisor_Initial', max_length=50, null=True)),
                ('founded_year', models.TextField(blank=True, db_column='Founded_Year', null=True)),
            ],
            options={
                'db_table': 'clubs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClubsEvents',
            fields=[
                ('club_id', models.CharField(db_column='Club_ID', max_length=10, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, db_column='Role', max_length=50, null=True)),
                ('budget_share', models.IntegerField(blank=True, db_column='Budget_share', null=True)),
            ],
            options={
                'db_table': 'clubs_events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('registration_id', models.CharField(db_column='Registration_ID', max_length=10, primary_key=True, serialize=False)),
                ('attendance_code', models.TextField(blank=True, db_column='Attendance_code', null=True)),
                ('attendance', models.CharField(blank=True, db_column='Attendance', max_length=7, null=True)),
                ('attendance_time', models.DateTimeField(blank=True, db_column='Attendance_time', null=True)),
                ('rating', models.PositiveIntegerField(blank=True, db_column='Rating', null=True)),
                ('comment', models.CharField(blank=True, db_column='Comment', max_length=255, null=True)),
                ('payment_status', models.CharField(blank=True, db_column='Payment_status', max_length=7, null=True)),
            ],
            options={
                'db_table': 'event_registration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.CharField(db_column='Event_ID', max_length=10, primary_key=True, serialize=False)),
                ('event_name', models.CharField(blank=True, db_column='Event_Name', max_length=50, null=True)),
                ('event_date', models.DateTimeField(blank=True, db_column='Event_Date', null=True)),
                ('event_details', models.CharField(blank=True, db_column='Event_details', max_length=255, null=True)),
                ('event_type', models.CharField(blank=True, db_column='Event_type', max_length=50, null=True)),
                ('event_fee', models.IntegerField(blank=True, db_column='Event_fee', null=True)),
                ('venue', models.CharField(blank=True, db_column='Venue', max_length=50, null=True)),
                ('budget', models.IntegerField(blank=True, db_column='Budget', null=True)),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('expenses_id', models.CharField(db_column='Expenses_ID', max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
                ('amount', models.IntegerField(blank=True, db_column='Amount', null=True)),
            ],
            options={
                'db_table': 'expenses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('loan_id', models.CharField(db_column='Loan_ID', max_length=10, primary_key=True, serialize=False)),
                ('borrow_date', models.DateTimeField(blank=True, db_column='Borrow_date', null=True)),
                ('return_date', models.DateTimeField(blank=True, db_column='return_date', null=True)),
            ],
            options={
                'db_table': 'loans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.CharField(db_column='Role_ID', max_length=10, primary_key=True, serialize=False)),
                ('role', models.CharField(db_column='Role', max_length=50)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.CharField(db_column='Student_ID', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('department', models.CharField(blank=True, db_column='Department', max_length=50, null=True)),
                ('personality_type', models.CharField(blank=True, db_column='Personality_type', max_length=50, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('volunteer_id', models.CharField(db_column='Volunteer_ID', max_length=10, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, db_column='Role', max_length=255, null=True)),
                ('budget_allocated', models.IntegerField(blank=True, db_column='Budget_allocated', null=True)),
            ],
            options={
                'db_table': 'volunteers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClubsMembers',
            fields=[
                ('club', models.ForeignKey(db_column='Club_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.clubs')),
                ('joining_date', models.DateTimeField(blank=True, db_column='Joining_date', null=True)),
            ],
            options={
                'db_table': 'clubs_members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClubsRegistration',
            fields=[
                ('club', models.ForeignKey(db_column='Club_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.clubs')),
                ('payment_status', models.CharField(blank=True, db_column='Payment_status', max_length=7, null=True)),
            ],
            options={
                'db_table': 'clubs_registration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('student', models.ForeignKey(db_column='Student_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.students')),
                ('skill', models.CharField(db_column='Skill', max_length=50)),
            ],
            options={
                'db_table': 'skills',
                'managed': False,
            },
        ),
    ]
